name: Linux

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}
    container:
      image: fedora:43

    permissions:
      contents: write

    env:
      PKG_CONFIG_ALLOW_CROSS: 1
      CARGO_TERM_COLOR: always
      BIN_NAME: listenmoe

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Install build deps
        run: |
          dnf -y update
          dnf -y install \
            mold alsa-lib-devel libgpg-error-devel clang pkg-config nettle-devel \
            cairo-devel gcc git glib2-devel gtk4-devel libadwaita-devel make \
            openssl-devel pango-devel pkg-config pkgconf-pkg-config \
            rustup

          rustup-init -y --profile minimal --default-toolchain stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          "$HOME/.cargo/bin/rustup" target add x86_64-unknown-linux-gnu
          "$HOME/.cargo/bin/rustup" target add aarch64-unknown-linux-gnu

      - name: Tag
        id: tag
        shell: bash
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            echo "TAG_NAME=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
          else
            latest_tag=$(git describe --tags --abbrev=0)
            echo "TAG_NAME=$latest_tag" >> "$GITHUB_ENV"
          fi

      - name: Build (release)
        run: cargo build --release --target ${{ matrix.target }} --features setup

      - name: List produced binary
        run: ls -R target/${{ matrix.target }}/release

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ env.BIN_NAME }}

      - name: Release
        if: ${{ env.TAG_NAME != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: target/${{ matrix.target }}/release/${{ env.BIN_NAME }}
          overwrite_files: true
